version: '3'
services:
  yelb-ui:
    image: 'ghcr.io/alexgoller/illumio-yelb/yelb-ui:latest'
    depends_on:
      - yelb-appserver
    ports:
      - '80:80'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  yelb-appserver:
    image: 'ghcr.io/alexgoller/illumio-yelb/yelb-appserver:latest'
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-server:
    image: 'ghcr.io/alexgoller/illumio-yelb/redis-server:latest'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  yelb-db:
    image: 'ghcr.io/alexgoller/illumio-yelb/yelb-db:latest'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  yelb-network:
    driver: overlay
